version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
      - chmod +x publish.sh
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ./publish.sh
cache:
  paths:
  - /root/.npm/**/*
