name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://npm.pkg.github.com'
        scope: '@variocube'
        always-auth: true
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
    - run: npm run build
